* subed news
** Version 1.0.18 - 2022-11-08 - Sacha Chua

New function subed-parse-file.

** Version 1.0.17 - 2022-11-07 - Sacha Chua

New command subed-align in the subed-align.el file lets you use aeneas
for forced alignment. This can assign timestamps to each line of text.

VTT files can now have optional cue identifiers. A cue identifier is a
line of text before the timestamps that can identify the cue. It
should not contain "-->".

** Version 1.0.16 - 2022-10-26 - Sacha Chua

When you load word data, subtitle words that were successfully matched
with the word-level timestamps will now be highlighted so that it's
easier to split at them.

** Version 1.0.15 - 2022-10-26 - Sacha Chua

Added support for SRV2 files in subed-word-data.el. You can use
subed-word-data-load-from-file to load word-level timing data from
SRV2 files or add subed-word-data-load-maybe to the subed-mode-hook.

VTT no longer assumes that the start of the file is part of
the first subtitle.

VTT and SRT are now less confused by spaces at the end of a subtitle
when splitting.

** Version 1.0.14 - 2022-10-25 - Sacha Chua

Delete the CPS overlay when disabling it

** Version 1.0.13 - 2022-10-25 - Sacha Chua

Fixed TSV fontlocking.
Improved subed-convert so that the new buffer is also visiting a file.

** Version 1.0.12 - 2022-10-23 - Sacha Chua

Added new command ~subed-convert~.

** Version 1.0.11 - 2022-10-23 - Sacha Chua

Added subed-tsv.el for Audacity label exports. Use M-x subed-tsv-mode to load it.

** Version 1.0.10 - 2022-09-20 - Sacha Chua

Use - instead of : in mpv socket names to see if that will make it work better on Microsoft Windows.

** Version 1.0.9 - 2022-09-14 - Sacha Chua

- Consolidated the different faces to subed-id-face, subed-time-face,
  and subed-time-separator-face. Added tests for font-locking. Dropped
  text font-locking for now since we didn't have a good regular
  expression for it.

  Obsolete:
  - subed-srt-id-face
  - subed-srt-time-face
  - subed-srt-time-separator-face
  - subed-srt-text-face
  - subed-vtt-id-face
  - subed-vtt-time-face
  - subed-vtt-time-separator-face
  - subed-vtt-text-face
  - subed-ass-id-face
  - subed-ass-time-face
  - subed-ass-time-separator-face
  - subed-ass-text-face
  
Thanks to Igor for the bug report!

** Version 1.0.8 - 2022-09-08 - Sacha Chua

- Added support for SRT comment syntax thanks to mbork.
  http://mbork.pl/2022-09-05_Comments_in_srt_files

** Version 1.0.6 - 2022-07-22 - Sacha Chua

- Allow mm:ss.000 (optional hours) when validating VTT files.
- Use just the buffer name hash when naming the MPV socket.

** Version 1.0.3 - 2022-02-07 - Sacha Chua

subed now tries to avoid sorting already-sorted buffers, which should
reduce interference with mark rings and other things.

** Version 1.0.1 - 2022-02-01 - Sacha Chua

Added obsolete function aliases in case people are calling
format-specific functions in their code.

** Version 1.0.0 - 2022-01-02 - Sacha Chua

Format-specific modes are now initialized with =(subed-srt-mode)=,
=(subed-vtt-mode)=, or =(subed-ass-mode)= instead of the corresponding
=(subed-vtt--init)= functions.

I implemented the format-specific functions with =cl-defmethod=, so if
you have any code that refers to functions like
=subed-vtt--timestamp-to-msecs=, you will need to change your code to
use generic functions such as =subed-timestamp-to-msecs=.

