* subed news
** Version 1.0.13 - 2022-10-25 - Sacha Chua

Fixed TSV fontlocking.
Improved subed-convert so that the new buffer is also visiting a file.

** Version 1.0.12 - 2022-10-23 - Sacha Chua

Added new command ~subed-convert~.

** Version 1.0.11 - 2022-10-23 - Sacha Chua

Added subed-tsv.el for Audacity label exports. Use M-x subed-tsv-mode to load it.

** Version 1.0.10 - 2022-09-20 - Sacha Chua

Use - instead of : in mpv socket names to see if that will make it work better on Microsoft Windows.

** Version 1.0.9 - 2022-09-14 - Sacha Chua

- Consolidated the different faces to subed-id-face, subed-time-face,
  and subed-time-separator-face. Added tests for font-locking. Dropped
  text font-locking for now since we didn't have a good regular
  expression for it.

  Obsolete:
  - subed-srt-id-face
  - subed-srt-time-face
  - subed-srt-time-separator-face
  - subed-srt-text-face
  - subed-vtt-id-face
  - subed-vtt-time-face
  - subed-vtt-time-separator-face
  - subed-vtt-text-face
  - subed-ass-id-face
  - subed-ass-time-face
  - subed-ass-time-separator-face
  - subed-ass-text-face
  
Thanks to Igor for the bug report!

** Version 1.0.8 - 2022-09-08 - Sacha Chua

- Added support for SRT comment syntax thanks to mbork.
  http://mbork.pl/2022-09-05_Comments_in_srt_files

** Version 1.0.6 - 2022-07-22 - Sacha Chua

- Allow mm:ss.000 (optional hours) when validating VTT files.
- Use just the buffer name hash when naming the MPV socket.

** Version 1.0.3 - 2022-02-07 - Sacha Chua

subed now tries to avoid sorting already-sorted buffers, which should
reduce interference with mark rings and other things.

** Version 1.0.1 - 2022-02-01 - Sacha Chua

Added obsolete function aliases in case people are calling
format-specific functions in their code.

** Version 1.0.0 - 2022-01-02 - Sacha Chua

Format-specific modes are now initialized with =(subed-srt-mode)=,
=(subed-vtt-mode)=, or =(subed-ass-mode)= instead of the corresponding
=(subed-vtt--init)= functions.

I implemented the format-specific functions with =cl-defmethod=, so if
you have any code that refers to functions like
=subed-vtt--timestamp-to-msecs=, you will need to change your code to
use generic functions such as =subed-timestamp-to-msecs=.

